[toolchain]
channel = "nightly-2024-01-16"
components = []
targets = [
    # iOS
    "aarch64-apple-ios",
    "x86_64-apple-ios",
    # "aarch64-apple-ios-sim",
    # Android
    "aarch64-linux-android",
    "x86_64-linux-android",
    # Linux
    # "x86_64-unknown-linux-gnu",
    # macOS
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    # Windows
    # "x86_64-pc-windows-gnu",
    # "x86_64-pc-windows-msvc"
]
profile = "default"
